version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: gym_project
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  first_service:
    build:
      context: ./first_service
    command: python main.py
    volumes:
      - ./first_service:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/gym_project

  second_service:
    build:
      context: ./second_service
    command: gunicorn -b 0.0.0.0:8001 second_service:app
    volumes:
      - ./second_service:/app
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgres://user:password@db:5432/gym_project

  celery_worker:
    build:
      context: ./second_service
    command: celery -A celery worker --loglevel=info
    volumes:
      - ./second_service:/app
    depends_on:
      - second_service
      - rabbitmq
